name: Testes da API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
      timeout-minutes: 5
        
    - name: Executar testes
      run: |
        pytest test_main.py -v
      timeout-minutes: 5 